title: Assets
modelClass: Unisa\Assets\Models\Assets
list: $/unisa/assets/models/assets/columns.yaml
recordUrl: 'unisa/assets/assets/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
