title: Pages
modelClass: Unisa\Pages\Models\Pages
list: $/unisa/pages/models/pages/columns.yaml
recordUrl: 'unisa/pages/pages/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
