name: Pages
modelClass: Unisa\Pages\Models\Page
form: $/unisa/pages/models/page/fields.yaml
defaultRedirect: unisa/pages/pages
create:
    redirect: 'unisa/pages/pages/update/:id'
    redirectClose: unisa/pages/pages
update:
    redirect: unisa/pages/pages
    redirectClose: unisa/pages/pages
preview: {  }
